## Introduction

### Print and format

In [1]:
print(10)

10


In [2]:
print("NISKA")

NISKA


In [3]:
a = 10
print(10)

10


In [4]:
a = input()
print(a)

2
2


In [5]:
n = input('Unesite vrednost n: ')

Unesite vrednost n: 123


In [6]:
n = 10
print('Vrednost promenljive n je {}'.format(n))

Vrednost promenljive n je 10


In [7]:
a = 5
b = 6
print('a = {}, b = {}'.format(a, b))

a = 5, b = 6


### Read & write

In [8]:
with open('points.txt') as f:
    print(f.read())

Point,x,y,Color
A,37,34,red
B,1,12,NaN
C,6,37,NaN
D,32,11,yellow
E,8,30,yellow
F,19,10,NaN
G,21,44,yellow
H,21,43,NaN
I,2,5,yellow
J,14,33,red
K,1,31,red
L,13,25,blue
M,0,4,NaN
N,11,16,blue
O,43,28,red
P,5,40,NaN
Q,1,41,red
R,45,49,yellow
S,2,37,red
T,37,45,red
U,18,40,NaN
V,43,24,red
W,0,9,NaN
X,16,2,red
Y,46,25,red
Z,36,9,blue


In [9]:
with open('points.txt') as f:
    print(f.readline())

Point,x,y,Color



In [10]:
try:
    with open('ne_postojim.txt') as f:
        print(f.read())
except:
    print('Greska prilikom ucitavanja datoteke!')

Greska prilikom ucitavanja datoteke!


In [11]:
try:
    with open('upisi.txt', 'w') as f:
        f.write('Ovo je prva lekcija na Data Science kursu')
except:
    print('Doslo je do greske!')

### If-else, for & while

In [12]:
godina = 2022
if (godina % 4 == 0 and godina % 100 != 0) or (godina % 400 == 0):
    print('Godina {} je prestupna'.format(godina))
else:
    print('Godina {} je prosta'.format(godina))

Godina 2022 je prosta


In [13]:
for i in range(0,5):
    print(i)

0
1
2
3
4


In [14]:
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


### Lists

A list is of an ordered collection data type that is mutable which means it can be easily modified and we can change its data values and a list can be indexed, sliced, and changed and each element can be accessed using its index value in the list. The following are the main characteristics of a List:
</br>
* The list is an ordered collection of data types.
* The list is mutable.
* List are dynamic and can contain objects of different data types.
* List elements can be accessed by index number.

In [15]:
l = [1, 2, 3, 4]
print(l)

[1, 2, 3, 4]


In [16]:
print(l[0], l[-1])

1 4


In [17]:
n = len(l)
print('Length: {}'.format(n))

Length: 4


In [18]:
for elem in l:
    print(elem)

1
2
3
4


In [19]:
[elem**2 for elem in l]

[1, 4, 9, 16]

In [20]:
l = [1, 5, 2, 4, 3]
l.sort()
print(l)

[1, 2, 3, 4, 5]


In [21]:
l.append(6)
print(l)

[1, 2, 3, 4, 5, 6]


In [22]:
list1 = [1, 2, 3, 4]
list2 = ['a', 'b', 'c', 'd']
zip_list = zip(list1, list2)

In [23]:
list(zip_list)

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]

In [24]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8]


### Matrices

In [25]:
matrix = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [26]:
print(matrix[2][2])

9


### Strings

In [27]:
text = 'ABCDE'

for c in text:
    print(c)

A
B
C
D
E


In [28]:
text + 'F'

'ABCDEF'

In [29]:
text

'ABCDE'

In [30]:
text[0]

'A'

In [31]:
' '.join(['Data', 'Science'])

'Data Science'

### Tuples

 A tuple is an ordered and an immutable data type which means we cannot change its values and tuples are written in round brackets. We can access tuple by referring to the index number inside the square brackets.  The following are the main characteristics of a Tuple:
</br>
* Tuples are immutable and can store any type of data type.
* it is defined using ().
* it cannot be changed or replaced as it is an immutable data type.

In [32]:
t = (1, 2, 3, 4)
print(t)

(1, 2, 3, 4)


In [33]:
t[0]

1

### Sets

In [34]:
s = set([1, 2, 3, 4])
print(s)

{1, 2, 3, 4}


### Dictionaries

In [35]:
dict = {
    'a': 1,
    'b': 2
}

print(dict)

{'a': 1, 'b': 2}


In [36]:
dict['a']

1

In [37]:
dict['c'] = 3
print(dict)

{'a': 1, 'b': 2, 'c': 3}


### Functions

In [38]:
def minimum_maximum(a, b):
    minimum = min(a,b)
    maximum = max(a,b)
    return (minimum, maximum)

In [39]:
a = 10
b = 6.7

(minimum, maximum) = minimum_maximum(a, b)
print(minimum, maximum)

6.7 10


## Numpy

### Works with multidimensional arrays and performs mathematical operations on vectors

[Koristan tutorijal](https://numpy.org/doc/stable/user/quickstart.html)

An array is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together. This makes it easier to calculate the position of each element by simply adding an offset to a base value, i.e., the memory location of the first element of the array (generally denoted by the name of the array). The following are the main characteristics of an Array:
</br>
* An array is an ordered collection of the similar data types.
* An array is mutable.
* An array can be accessed by using its index number.

In [40]:
import numpy as np

In [41]:
a = np.array([1, 2, 3])
M = np.array([[1, 2, 3], [4, 5, 6]], dtype='float32')

print('Array a:')
print(a)
print('shape =', a.shape)
print('size =', a.size)
print('ndim =', a.ndim)
print('dtype =', a.dtype, end='\n\n')

print('Matrix M:')
print(M)
print('shape =', M.shape)
print('size =', M.size)
print('ndim =', M.ndim)
print('dtype =', M.dtype)

Array a:
[1 2 3]
shape = (3,)
size = 3
ndim = 1
dtype = int32

Matrix M:
[[1. 2. 3.]
 [4. 5. 6.]]
shape = (2, 3)
size = 6
ndim = 2
dtype = float32


In [42]:
a1 = np.arange(1, 10, 2)
a2 = np.linspace(1, 3, 21)
a3 = np.zeros(6)
a4 = np.random.uniform(2, 5, 5)

print('a1 =', a1)
print('a2 =', a2)
print('a3 =', a3)
print('a4 =', a4)

M1 = np.ones((2, 3))
M2 = np.eye(3)
M3 = np.diag([4, 3, 2, 1])
M4 = np.random.randn(4, 3)

print('M1 =\n', M1)
print('M2 =\n', M2)
print('M3 =\n', M3)
print('M4 =\n', M4)

a1 = [1 3 5 7 9]
a2 = [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3. ]
a3 = [0. 0. 0. 0. 0. 0.]
a4 = [4.77570051 3.85507862 3.89099555 4.06623583 2.88051962]
M1 =
 [[1. 1. 1.]
 [1. 1. 1.]]
M2 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
M3 =
 [[4 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 1]]
M4 =
 [[-0.05856912  0.71104533 -0.95627551]
 [ 1.26814759  0.75203713  1.259807  ]
 [ 0.7950739  -0.81703996  1.0150581 ]
 [ 0.09270409 -1.0606544   2.70192705]]


In [43]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.vstack((x, y)))
print(np.hstack((x, y)))
print(np.sum(x * y))
print(np.min(x))
print(y.max())
print(x[x > 1.5])
print(x+y)
print(np.sin(x))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
32
1
6
[2 3]
[5 7 9]
[0.84147098 0.90929743 0.14112001]


In [44]:
M1 = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
M2 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
print('M1 + M2 =\n', M1 + M2)
print('M1 * M2 =\n', M1 * M2)
print('M1 x M2 =\n', M1.dot(M2), '=\n', np.dot(M1, M2))
print('transpose(M1) =\n', M1.T, '=\n', M1.transpose())
print('sin(M1) =\n', np.sin(M1))
print('exp(M2) =\n', np.exp(M2))

M1 + M2 =
 [[ 3  7 11]
 [15 19 23]
 [27 31 35]]
M1 * M2 =
 [[  2  12  30]
 [ 56  90 132]
 [182 240 306]]
M1 x M2 =
 [[ 96 114 132]
 [240 294 348]
 [384 474 564]] =
 [[ 96 114 132]
 [240 294 348]
 [384 474 564]]
transpose(M1) =
 [[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]] =
 [[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
sin(M1) =
 [[ 0.84147098  0.14112001 -0.95892427]
 [ 0.6569866   0.41211849 -0.99999021]
 [ 0.42016704  0.65028784 -0.96139749]]
exp(M2) =
 [[7.38905610e+00 5.45981500e+01 4.03428793e+02]
 [2.98095799e+03 2.20264658e+04 1.62754791e+05]
 [1.20260428e+06 8.88611052e+06 6.56599691e+07]]


In [45]:
#Broadcasting
M = np.array([[1, 2, 3], [4, 5, 6]])
x = np.array([10, 20, 30])
print(M + x)

[[11 22 33]
 [14 25 36]]


In [46]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3], [4, 6, 6]])

print(np.array_equal(A, B))
print(A == B)

print(A.reshape(3, 2))

print(A.flatten())

print(np.sum(B[B == 6]))

False
[[ True  True  True]
 [ True False  True]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
12


## Pandas

### Works with data frames and series and performs data analysis

[Koristan tutorijal](https://pandas.pydata.org/pandas-docs/dev/user_guide/index.html)

In [47]:
import pandas as pd

In [48]:
pd.read_csv('points.csv')

Point   x   y   Color
0      A  37  34     red
1      B   1  12     NaN
2      C   6  37     NaN
3      D  32  11  yellow
4      E   8  30  yellow
5      F  19  10     NaN
6      G  21  44  yellow
7      H  21  43     NaN
8      I   2   5  yellow
9      J  14  33     red
10     K   1  31     red
11     L  13  25    blue
12     M   0   4     NaN
13     N  11  16    blue
14     O  43  28     red
15     P   5  40     NaN
16     Q   1  41     red
17     R  45  49  yellow
18     S   2  37     red
19     T  37  45     red
20     U  18  40     NaN
21     V  43  24     red
22     W   0   9     NaN
23     X  16   2     red
24     Y  46  25     red
25     Z  36   9    blue

In [49]:
pd.DataFrame({'kolona_1': ['Ovo je prva lekcija na Data Science kursu']}).to_csv('upisi.csv')